substitutions:
  device_name: spa-controller

esphome:
  name: ${device_name}
  friendly_name: Spa Controller

esp32:
  board: featheresp32-s2
  framework:
    type: arduino

# Import Gecko Spa component from GitHub
external_components:
  - source: github://zteifel/esphome-gecko
    components: [gecko_spa]

logger:
  level: DEBUG
  baud_rate: 0

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

# UART connection to Arduino I2C Proxy
uart:
  id: arduino_uart
  tx_pin: GPIO5
  rx_pin: GPIO16
  baud_rate: 115200
  rx_buffer_size: 512

# Gecko Spa component
gecko_spa:
  id: spa
  uart_id: arduino_uart

# Climate control
climate:
  - platform: gecko_spa
    gecko_spa_id: spa
    name: "Spa"

# Switches
switch:
  - platform: gecko_spa
    gecko_spa_id: spa
    type: light
    name: "Spa Light"
    icon: "mdi:lightbulb"

  - platform: gecko_spa
    gecko_spa_id: spa
    type: pump
    name: "Spa Pump"
    icon: "mdi:pump"

  - platform: gecko_spa
    gecko_spa_id: spa
    type: circulation
    name: "Spa Circulation"
    icon: "mdi:rotate-3d-variant"

# Program selector
select:
  - platform: gecko_spa
    gecko_spa_id: spa
    name: "Spa Program"
    icon: "mdi:format-list-bulleted"

# Status sensors
binary_sensor:
  - platform: gecko_spa
    gecko_spa_id: spa
    type: standby
    name: "Spa Standby"
    icon: "mdi:power-standby"

  - platform: gecko_spa
    gecko_spa_id: spa
    type: connected
    name: "Spa Connected"
    icon: "mdi:connection"
    device_class: connectivity

# Optional: Button to manually request status
button:
  - platform: template
    name: "Refresh Spa Status"
    icon: "mdi:refresh"
    on_press:
      - lambda: |-
          id(spa).request_status();
